import { TQuestion } from "./types";

export const quizQuestions: TQuestion[] = [
  {
    id: 1,
    question: "Die meisten einheimischen Süßwasserfische gehören zu den ...?",
    option1: "Knochenfischen",
    option2: "Knorpelfischen",
    option3: "Rundmäulern",
  },
  {
    id: 2,
    question: "Wozu dienen die Barteln?",
    option1: "Als Geschmacks- und Tastorgan",
    option2: "Zur Fortbewegung",
    option3: "Als Fresswerkzeuge",
  },
  {
    id: 3,
    question:
      "Augen sind wichtig für den Beutefang. Bei welcher Fischart besonders?",
    option1: "Hecht",
    option2: "Aal",
    option3: "Wels",
  },
  {
    id: 4,
    question: "Wo befindet sich das Herz beim Fisch?",
    option1: "In kehlständiger Lage",
    option2: "Oberhalb der Niere",
    option3: "Am hinteren Teil der Schwimmblase",
  },
  {
    id: 5,
    question:
      "Wie werden die Atmungsorgane unserer heimischen Fische bezeichnet?",
    option1: "Kiemen",
    option2: "Lungen",
    option3: "Schwimmblase",
  },
  {
    id: 6,
    question: "Welche Flosse ist das Hauptantriebsorgan der Fische?",
    option1: "Schwanzflosse",
    option2: "Bauchflosse",
    option3: "Brustflosse",
  },
  {
    id: 7,
    question: "Was haben alle Salmoniden gemeinsam?",
    option1: "Eine Fettflosse",
    option2: "Ein unterständiges Maul",
    option3: "Barteln",
  },
  {
    id: 8,
    question: "Der Karpfen gehört zu den ...?",
    option1: "Knochenfischen",
    option2: "Knorpelfischen",
    option3: "Rundmäulern",
  },
  {
    id: 9,
    question: "Das Neunauge gehört zu den ...?",
    option1: "Rundmäulern",
    option2: "Knochenfischen hält die Schuppen",
    option3: "Knorpelfischen",
  },
  {
    id: 10,
    question: "Die Schleimhaut eines Fisches ...",
    option1: "schützt den Fisch vor äußeren Einflüssen.",
    option2: "zusammen.",
    option3: "sorgt für die Färbung des Fisches.",
  },
  {
    id: 11,
    question: "Wozu dient dem Fisch die Seitenlinie?",
    option1: "Als Sinnesorgan",
    option2: "Sie hat keine besondere Funktion",
    option3: "Zur Sauerstoffaufnahme",
  },
  {
    id: 12,
    question: "Woher haben die Neunaugen ihren Namen?",
    option1:
      "Beim erwachsenen Tier werden je Körperseite sieben Kiemenöffnungen und die Nasenöffnung dem echten Auge zugerechnet.",
    option2:
      "Die Tiere verfügen auf jeder Seite über acht Pigmentflecken und ein Auge.",
    option3: "Die Tiere besitzen insgesamt neun Pigmentflecken.",
  },
  {
    id: 13,
    question:
      "Worin unterscheidet sich die männliche von der weiblichen Äsche ?",
    option1: "Die männliche Äsche besitzt eine längere Rückenflosse",
    option2: "Die männliche Äsche besitzt keine Brustflossen",
    option3: "In der Zahnformel",
  },
  {
    id: 14,
    question: "Wie gut ist der Geruchssinn bei dem Aal ausgeprägt?",
    option1: "Sehr gut",
    option2: "Schlecht",
    option3: "Mittelmäßig",
  },
  {
    id: 15,
    question: "Was versteht man unter einem Laichhaken?",
    option1:
      "Hakenartige Verformung des Unterkiefers bei Milchnern der Lachsartigen",
    option2: "Hilfsgerät zum Anlanden von laichreifen Fischen",
    option3: "Gerät zum Beseitigen unerwünschter Laichnester",
  },
  {
    id: 16,
    question: "Welche Fische haben keinen Magen?",
    option1: "Karausche, Schleie",
    option2: "Hecht, Barsch",
    option3: "Zander, Wels",
  },
  {
    id: 17,
    question: "Wieviel Bartfäden hat die Schleie?",
    option1: "Zwei",
    option2: "Keine",
    option3: "Vier",
  },
  {
    id: 18,
    question: "Eingebettet in der Leber liegt... ?",
    option1: "die Gallenblase",
    option2: "der Magen",
    option3: "die Niere",
  },
  {
    id: 19,
    question: "Die Besamung der Eier des Karpfens erfolgt ... ?",
    option1: "außerhalb des Körpers",
    option2: "innerhalb des Körpers",
    option3: "durch Selbstbefruchtung",
  },
  {
    id: 20,
    question: "Welche Fischart hat relativ kleine Augen?",
    option1: "Wels",
    option2: "Rotauge",
    option3: "Rotfeder",
  },
  {
    id: 21,
    question: "Welche Fischart hat eine pfeilförmige Körperform?",
    option1: "Hecht",
    option2: "Plötze",
    option3: "Aal",
  },
  {
    id: 22,
    question: "Welche Fischart hat eine Fettflosse?",
    option1: "Regenbogenforelle",
    option2: "Bitterling",
    option3: "Barsch",
  },
  {
    id: 23,
    question: "Welche Fischart hat eine Fettflosse?",
    option1: "Zwergwels",
    option2: "Europäischer Wels",
    option3: "Quappe",
  },
  {
    id: 24,
    question:
      "Welche Fischart lebt in der hauptsächlichen Abwachszeit im Süßwasser und laicht im Meer?",
    option1: "Aal",
    option2: "Lachs",
    option3: "Quappe",
  },
  {
    id: 25,
    question:
      "Welche Fischart lebt in der hauptsächlichen Abwachszeit im Meer un laicht im Süßwasser?",
    option1: "Lachs",
    option2: "Quappe",
    option3: "Barbe",
  },
  {
    id: 26,
    question:
      "Welcher cyprinidenartige Fisch ist im ausgewachsenen Alter ein Raubfisch?",
    option1: "Rapfen",
    option2: "Karpfen",
    option3: "Schleie",
  },
  {
    id: 27,
    question:
      "Welche Fischart besitzt Stachelstrahlen in der ersten Rückenflosse?",
    option1: "Barsch",
    option2: "Forelle",
    option3: "Kleine Maräne",
  },
  {
    id: 28,
    question: "Welche der genannten Arten besitzt keine Schuppen?",
    option1: "Bachneunauge",
    option2: "Moderlieschen",
    option3: "Döbel",
  },
  {
    id: 29,
    question: "Welche der genannten Arten hat einen Saugmund mit Hornzähnen?",
    option1: "Neunauge",
    option2: "Steinbeiẞer",
    option3: "Gründling",
  },
  {
    id: 30,
    question:
      "Welche Fische rauben hauptsächlich nachts, wenn das Sehvermögen eine nicht so große Rolle spielt?",
    option1: "Wels, Aal",
    option2: "Saibling, Lachs",
    option3: "Hecht, Zander",
  },
  {
    id: 31,
    question:
      "Welche Fischart besitzt einen durch Verbindung von Afterflosse und Rückenflosse entstandenen Flossensaum?",
    option1: "Aal",
    option2: "Zwergwels",
    option3: "Schmerle",
  },
  {
    id: 32,
    question:
      "Bei welcher im Süßwasser lebenden Fischart trägt das Männchen ei überwiegend leuchtend rotes Hochzeitskleid?",
    option1: "Dreistachliger Stichling",
    option2: "Flussbarsch",
    option3: "Rotbarsch",
  },
  {
    id: 33,
    question: "Welcher Fisch legt seine Eier in Muscheln ab?",
    option1: "Bitterling",
    option2: "Stichling",
    option3: "Stint",
  },
  {
    id: 34,
    question: "Welcher Fisch besitzt während der Laichzeit giftigen Rogen?",
    option1: "Barbe",
    option2: "Karpfen",
    option3: "Hecht",
  },
  {
    id: 35,
    question:
      "Welcher Fisch kann bei Sauerstoffmangel durch den Darm zusätzlich Sauerstoff aufnehmen?",
    option1: "Schlammpeitzger",
    option2: "Elritze",
    option3: "Gründling",
  },
  {
    id: 36,
    question: 'Wie unterscheidet sich der "Zwergwels" vom "Europäischen Wels"?',
    option1: "Der Zwergwels hat eine Fettflosse.",
    option2: "Die Schwanzflosse des Zwergwelses ist größer.",
    option3: "Der Zwergwels hat keine Schwimmblase.",
  },
  {
    id: 37,
    question:
      "Welcher Fisch im Land Brandenburg lebt im Freiwasser tiefer, klarer Seen?",
    option1: "Maräne",
    option2: "Schleie",
    option3: "Karpfen",
  },
  {
    id: 38,
    question: "Welche Fischart bevorzugt nährstoffreiche Gewässer?",
    option1: "Karpfen",
    option2: "Bachforelle",
    option3: "Mühlkoppe",
  },
  {
    id: 39,
    question: "Zu welcher Ordnung gehört die Quappe?",
    option1: "Dorschartige",
    option2: "Barschartige",
    option3: "Karpfenartige",
  },
  {
    id: 40,
    question: "Welche Fischarten zählen zu den Laichräubern?",
    option1: "Aal, Quappe",
    option2: "Hecht, Zander",
    option3: "Kleine Maräne, Stint",
  },
  {
    id: 41,
    question: "Welche Fischart verteidigt ihren Laichplatz?",
    option1: "Zander",
    option2: "Hecht",
    option3: "Karpfen",
  },
  {
    id: 42,
    question: "Zu der Familie der Karpfenfische (Cyprinidae) gehören ...?",
    option1: "Gründling, Döbel,",
    option2: "Aal, Hecht, Maräne.",
    option3: "Schlammpeitzger, Schmerle, Steinbeiẞer",
  },
  {
    id: 43,
    question: "Zu der Familie der Lachse (Salmonidae) gehören ...?",
    option1: "Rotfeder.",
    option2: "Zander, Kaulbarsch, Flussbarsch",
    option3: "Gründling, Barbe, Elritze",
  },
  {
    id: 44,
    question: "Wie ist die Maulstellung beim Döbel?",
    option1: "Bachforelle, Bachsaibling",
    option2: "Unterständig",
    option3: "Oberständig",
  },
  {
    id: 45,
    question:
      "Welcher einheimische Fisch kann sein Maul rüsselartig vorstülpen?",
    option1: "Endständig",
    option2: "Kleine Maräne",
    option3: "Hecht",
  },
  {
    id: 46,
    question: "Welcher Fisch hat einen gekielten Bauch?",
    option1: "Karpfen",
    option2: "Quappe",
    option3: "Bachforelle",
  },
  {
    id: 47,
    question: "Bei welcher Fischart ist die Schwanzflosse gerundet?",
    option1: "Rotfeder",
    option2: "Aal",
    option3: "Zander",
  },
  {
    id: 48,
    question: "Welche Fischart ist hochrückig?",
    option1: "Blei",
    option2: "Döbel",
    option3: "Barbe",
  },
  {
    id: 49,
    question: "Welche Flosse hat keine Flossenstrahlen?",
    option1: "Die Fettflosse der Bachforelle",
    option2: "Die Rückenflosse des Zanders",
    option3: "Die Rückenflosse des Flussbarsches",
  },
  {
    id: 50,
    question: "Welcher Fisch hat einen geringen Fettgehalt im Fleisch?",
    option1: "Hecht",
    option2: "Karpfen",
    option3: "Aal",
  },
  {
    id: 51,
    question: "Welcher Fisch betreibt Brutpflege?",
    option1: "Koppe",
    option2: "Karpfen",
    option3: "Maräne",
  },
  {
    id: 52,
    question:
      "Welche Fischart besitzt keine Stachelstrahlen im ersten Teil der Rückenflosse?",
    option1: "Hecht",
    option2: "Zander",
    option3: "Flussbarsch",
  },
  {
    id: 53,
    question: "Welcher Fisch riecht nach frischer grüner Gurke?",
    option1: "Stint",
    option2: "Steinbeißer",
    option3: "Koppe",
  },
  {
    id: 54,
    question: "Welche Fischart ist anfällig für die Bauchwassersucht?",
    option1: "Karpfen",
    option2: "Forelle",
    option3: "Zander",
  },
  {
    id: 55,
    question: "Wie äußert sich die Grieẞkörnchenkrankheit?",
    option1: "Durch weiße Punkte auf dem ganzen Körper",
    option2: "Durch weiße Punkte auf den Kiemen",
    option3: "Durch Glotzaugen",
  },
  {
    id: 56,
    question: "Wo schmarotzen Karpfenläuse?",
    option1: "Auf dem ganzen Körper",
    option2: "Nur auf den Kiemen",
    option3: "Im Darm",
  },
  {
    id: 57,
    question: "Was ist eine Karpfenlaus?",
    option1:
      "Ein Kleinkrebs, der auf der Bevorzugte Haut von Karpfenfischen Karpfennahrung parisitiert.",
    option2: "Bevorzugter Parasit bei Karpfen",
    option3: "Ein Fachausdruck für Fischläuse",
  },
  {
    id: 58,
    question: "Welche Krankheit ist für den Karpfen typisch ?",
    option1: "Bauchwassersucht",
    option2: "Rotmaulseuche",
    option3: "Blumenkohlgeschwulst",
  },
  {
    id: 59,
    question:
      'Im Mai fange ich einen Blei mit weißen "Körnchen" auf dem Kopf. Worum handelt es sich mit hoher Wahrscheinlichkeit?',
    option1: "Laichausschlag",
    option2: "Krankheit",
    option3: "Tarnfärbung",
  },
  {
    id: 60,
    question:
      'Was ist in der Fischerei unter dem Begriff "Messerrücken" zu verstehen?',
    option1: "Hungerform von Karpfenfischen, speziell beim Blei",
    option2: "Rücken des Blankaals",
    option3: "Bergspitzen unterseeischer Erhebungen",
  },
  {
    id: 61,
    question: "Wo parasitieren Fischegel?",
    option1: "Auf der Haut",
    option2: "Im Darm",
    option3: "In der Leibeshöhle",
  },
  {
    id: 62,
    question:
      "Worauf ist beim Kauf von Satzschleien und vor ihrem Aussatz besonders zu achten?",
    option1: "Auf Befall mit Kiemenkrebsen (Ergasilus)",
    option2: "Auf Reinrassigkeit",
    option3: "Auf günstige Anteile von Weibchen",
  },
  {
    id: 63,
    question:
      "Welche Maßnahmen können das seuchenbiologische Gleichgewicht im Gewässer beeinträchtigen?",
    option1: "Aussetzen gebietsfremder Fische, Einleitung organischer Abwässer",
    option2: "Starke Beangelung",
    option3: "Rohrernte im Winter",
  },
  {
    id: 64,
    question:
      "Was ruft bei der sogenannten Drehkrankheit die Drehbewegung hervor?",
    option1: "Einlagerung der Parasitensporen im Gleichgewichtsorgan",
    option2: "Versuche der Fische zur Abstoßung der Parasiten",
    option3: "Ermüdungserscheinungen des Fisches",
  },
  {
    id: 65,
    question: "Zu den Außenparasiten zählen ...?",
    option1: "Egel",
    option2: "Bandwürmer",
    option3: "Nematoden",
  },
  {
    id: 66,
    question: "Wodurch kann es zu Verpilzungen kommen?",
    option1: "Durch Verletzungen der Durch falsche Ernährung Schleimhaut",
    option2: "Durch falsche Ernährung",
    option3: "Durch Altersschwäche",
  },
  {
    id: 67,
    question:
      "Weshalb ist in vielen Gewässern Brandenburgs Aalbesatz notwendig?",
    option1: "Wegen fehlendem Aufstieg von Jungaalen.",
    option2: "Wegen zu geringer Bestände",
    option3: "Wegen der zu starken Befischung",
  },
  {
    id: 68,
    question: "Wie wird Hechtbesatz getätigt?",
    option1: "Einzeln in Ufernähe, wenn möglich über Krautbänken",
    option2: "Nur an einer Uferstelle",
    option3: "In kleinen Mengen im Freiwasser",
  },
  {
    id: 69,
    question:
      "Die Quappenbestände im Land Brandenburg sind stark zurückgegangen. Weshalb?",
    option1: "Die Vielzahl der Wehre versperrt die Wege zu den Laichgebieten.",
    option2: "Sie finden zu wenig Futter",
    option3: "Sie werden zu stark beangelt",
  },
];
