import { TQuestion } from "./types";

export const quizQuestions: TQuestion[] = [
  {
    id: 1,
    question: "Die meisten einheimischen Süßwasserfische gehören zu den ...?",
    option1: "Knochenfischen",
    option2: "Knorpelfischen",
    option3: "Rundmäulern",
  },
  {
    id: 2,
    question: "Wozu dienen die Barteln?",
    option1: "Als Geschmacks- und Tastorgan",
    option2: "Zur Fortbewegung",
    option3: "Als Fresswerkzeuge",
  },
  {
    id: 3,
    question:
      "Augen sind wichtig für den Beutefang. Bei welcher Fischart besonders?",
    option1: "Hecht",
    option2: "Aal",
    option3: "Wels",
  },
  {
    id: 4,
    question: "Wo befindet sich das Herz beim Fisch?",
    option1: "In kehlständiger Lage",
    option2: "Oberhalb der Niere",
    option3: "Am hinteren Teil der Schwimmblase",
  },
  {
    id: 5,
    question:
      "Wie werden die Atmungsorgane unserer heimischen Fische bezeichnet?",
    option1: "Kiemen",
    option2: "Lungen",
    option3: "Schwimmblase",
  },
  {
    id: 6,
    question: "Welche Flosse ist das Hauptantriebsorgan der Fische?",
    option1: "Schwanzflosse",
    option2: "Bauchflosse",
    option3: "Brustflosse",
  },
  {
    id: 7,
    question: "Was haben alle Salmoniden gemeinsam?",
    option1: "Eine Fettflosse",
    option2: "Ein unterständiges Maul",
    option3: "Barteln",
  },
  {
    id: 8,
    question: "Der Karpfen gehört zu den ...?",
    option1: "Knochenfischen",
    option2: "Knorpelfischen",
    option3: "Rundmäulern",
  },
  {
    id: 9,
    question: "Das Neunauge gehört zu den ...?",
    option1: "Rundmäulern",
    option2: "Knochenfischen hält die Schuppen",
    option3: "Knorpelfischen",
  },
  {
    id: 10,
    question: "Die Schleimhaut eines Fisches ...",
    option1: "schützt den Fisch vor äußeren Einflüssen.",
    option2: "zusammen.",
    option3: "sorgt für die Färbung des Fisches.",
  },
  {
    id: 11,
    question: "Wozu dient dem Fisch die Seitenlinie?",
    option1: "Als Sinnesorgan",
    option2: "Sie hat keine besondere Funktion",
    option3: "Zur Sauerstoffaufnahme",
  },
  {
    id: 12,
    question: "Woher haben die Neunaugen ihren Namen?",
    option1:
      "Beim erwachsenen Tier werden je Körperseite sieben Kiemenöffnungen und die Nasenöffnung dem echten Auge zugerechnet.",
    option2:
      "Die Tiere verfügen auf jeder Seite über acht Pigmentflecken und ein Auge.",
    option3: "Die Tiere besitzen insgesamt neun Pigmentflecken.",
  },
  {
    id: 13,
    question:
      "Worin unterscheidet sich die männliche von der weiblichen Äsche ?",
    option1: "Die männliche Äsche besitzt eine längere Rückenflosse",
    option2: "Die männliche Äsche besitzt keine Brustflossen",
    option3: "In der Zahnformel",
  },
  {
    id: 14,
    question: "Wie gut ist der Geruchssinn bei dem Aal ausgeprägt?",
    option1: "Sehr gut",
    option2: "Schlecht",
    option3: "Mittelmäßig",
  },
  {
    id: 15,
    question: "Was versteht man unter einem Laichhaken?",
    option1:
      "Hakenartige Verformung des Unterkiefers bei Milchnern der Lachsartigen",
    option2: "Hilfsgerät zum Anlanden von laichreifen Fischen",
    option3: "Gerät zum Beseitigen unerwünschter Laichnester",
  },
  {
    id: 16,
    question: "Welche Fische haben keinen Magen?",
    option1: "Karausche, Schleie",
    option2: "Hecht, Barsch",
    option3: "Zander, Wels",
  },
  {
    id: 17,
    question: "Wieviel Bartfäden hat die Schleie?",
    option1: "Zwei",
    option2: "Keine",
    option3: "Vier",
  },
  {
    id: 18,
    question: "Eingebettet in der Leber liegt... ?",
    option1: "die Gallenblase",
    option2: "der Magen",
    option3: "die Niere",
  },
  {
    id: 19,
    question: "Die Besamung der Eier des Karpfens erfolgt ... ?",
    option1: "außerhalb des Körpers",
    option2: "innerhalb des Körpers",
    option3: "durch Selbstbefruchtung",
  },
  {
    id: 20,
    question: "Welche Fischart hat relativ kleine Augen?",
    option1: "Wels",
    option2: "Rotauge",
    option3: "Rotfeder",
  },
  {
    id: 21,
    question: "Welche Fischart hat eine pfeilförmige Körperform?",
    option1: "Hecht",
    option2: "Plötze",
    option3: "Aal",
  },
  {
    id: 22,
    question: "Welche Fischart hat eine Fettflosse?",
    option1: "Regenbogenforelle",
    option2: "Bitterling",
    option3: "Barsch",
  },
  {
    id: 23,
    question: "Welche Fischart hat eine Fettflosse?",
    option1: "Zwergwels",
    option2: "Europäischer Wels",
    option3: "Quappe",
  },
  {
    id: 24,
    question:
      "Welche Fischart lebt in der hauptsächlichen Abwachszeit im Süßwasser und laicht im Meer?",
    option1: "Aal",
    option2: "Lachs",
    option3: "Quappe",
  },
  {
    id: 25,
    question:
      "Welche Fischart lebt in der hauptsächlichen Abwachszeit im Meer un laicht im Süßwasser?",
    option1: "Lachs",
    option2: "Quappe",
    option3: "Barbe",
  },
  {
    id: 26,
    question:
      "Welcher cyprinidenartige Fisch ist im ausgewachsenen Alter ein Raubfisch?",
    option1: "Rapfen",
    option2: "Karpfen",
    option3: "Schleie",
  },
  {
    id: 27,
    question:
      "Welche Fischart besitzt Stachelstrahlen in der ersten Rückenflosse?",
    option1: "Barsch",
    option2: "Forelle",
    option3: "Kleine Maräne",
  },
  {
    id: 28,
    question: "Welche der genannten Arten besitzt keine Schuppen?",
    option1: "Bachneunauge",
    option2: "Moderlieschen",
    option3: "Döbel",
  },
  {
    id: 29,
    question: "Welche der genannten Arten hat einen Saugmund mit Hornzähnen?",
    option1: "Neunauge",
    option2: "Steinbeiẞer",
    option3: "Gründling",
  },
  {
    id: 30,
    question:
      "Welche Fische rauben hauptsächlich nachts, wenn das Sehvermögen eine nicht so große Rolle spielt?",
    option1: "Wels, Aal",
    option2: "Saibling, Lachs",
    option3: "Hecht, Zander",
  },
  {
    id: 31,
    question:
      "Welche Fischart besitzt einen durch Verbindung von Afterflosse und Rückenflosse entstandenen Flossensaum?",
    option1: "Aal",
    option2: "Zwergwels",
    option3: "Schmerle",
  },
  {
    id: 32,
    question:
      "Bei welcher im Süßwasser lebenden Fischart trägt das Männchen ei überwiegend leuchtend rotes Hochzeitskleid?",
    option1: "Dreistachliger Stichling",
    option2: "Flussbarsch",
    option3: "Rotbarsch",
  },
  {
    id: 33,
    question: "Welcher Fisch legt seine Eier in Muscheln ab?",
    option1: "Bitterling",
    option2: "Stichling",
    option3: "Stint",
  },
  {
    id: 34,
    question: "Welcher Fisch besitzt während der Laichzeit giftigen Rogen?",
    option1: "Barbe",
    option2: "Karpfen",
    option3: "Hecht",
  },
  {
    id: 35,
    question:
      "Welcher Fisch kann bei Sauerstoffmangel durch den Darm zusätzlich Sauerstoff aufnehmen?",
    option1: "Schlammpeitzger",
    option2: "Elritze",
    option3: "Gründling",
  },
  {
    id: 36,
    question: 'Wie unterscheidet sich der "Zwergwels" vom "Europäischen Wels"?',
    option1: "Der Zwergwels hat eine Fettflosse.",
    option2: "Die Schwanzflosse des Zwergwelses ist größer.",
    option3: "Der Zwergwels hat keine Schwimmblase.",
  },
  {
    id: 37,
    question:
      "Welcher Fisch im Land Brandenburg lebt im Freiwasser tiefer, klarer Seen?",
    option1: "Maräne",
    option2: "Schleie",
    option3: "Karpfen",
  },
  {
    id: 38,
    question: "Welche Fischart bevorzugt nährstoffreiche Gewässer?",
    option1: "Karpfen",
    option2: "Bachforelle",
    option3: "Mühlkoppe",
  },
  {
    id: 39,
    question: "Zu welcher Ordnung gehört die Quappe?",
    option1: "Dorschartige",
    option2: "Barschartige",
    option3: "Karpfenartige",
  },
  {
    id: 40,
    question: "Welche Fischarten zählen zu den Laichräubern?",
    option1: "Aal, Quappe",
    option2: "Hecht, Zander",
    option3: "Kleine Maräne, Stint",
  },
  {
    id: 41,
    question: "Welche Fischart verteidigt ihren Laichplatz?",
    option1: "Zander",
    option2: "Hecht",
    option3: "Karpfen",
  },
  {
    id: 42,
    question: "Zu der Familie der Karpfenfische (Cyprinidae) gehören ...?",
    option1: "Gründling, Döbel, Rotfeder.",
    option2: "Aal, Hecht, Maräne.",
    option3: "Schlammpeitzger, Schmerle, Steinbeiẞer",
  },
  {
    id: 43,
    question: "Zu der Familie der Lachse (Salmonidae) gehören ...?",
    option1: "Bachforelle, Bachsaibling",
    option2: "Zander, Kaulbarsch, Flussbarsch",
    option3: "Gründling, Barbe, Elritze",
  },
  {
    id: 44,
    question: "Wie ist die Maulstellung beim Döbel?",
    option1: "Endständig",
    option2: "Unterständig",
    option3: "Oberständig",
  },
  {
    id: 45,
    question:
      "Welcher einheimische Fisch kann sein Maul rüsselartig vorstülpen?",
    option1: "Karpfen",
    option2: "Kleine Maräne",
    option3: "Hecht",
  },
  {
    id: 46,
    question: "Welcher Fisch hat einen gekielten Bauch?",
    option1: "Rotfeder",
    option2: "Quappe",
    option3: "Bachforelle",
  },
  {
    id: 47,
    question: "Bei welcher Fischart ist die Schwanzflosse gerundet?",
    option1: "Quappe",
    option2: "Aal",
    option3: "Zander",
  },
  {
    id: 48,
    question: "Welche Fischart ist hochrückig?",
    option1: "Blei",
    option2: "Döbel",
    option3: "Barbe",
  },
  {
    id: 49,
    question: "Welche Flosse hat keine Flossenstrahlen?",
    option1: "Die Fettflosse der Bachforelle",
    option2: "Die Rückenflosse des Zanders",
    option3: "Die Rückenflosse des Flussbarsches",
  },
  {
    id: 50,
    question: "Welcher Fisch hat einen geringen Fettgehalt im Fleisch?",
    option1: "Hecht",
    option2: "Karpfen",
    option3: "Aal",
  },
  {
    id: 51,
    question: "Welcher Fisch betreibt Brutpflege?",
    option1: "Koppe",
    option2: "Karpfen",
    option3: "Maräne",
  },
  {
    id: 52,
    question:
      "Welche Fischart besitzt keine Stachelstrahlen im ersten Teil der Rückenflosse?",
    option1: "Hecht",
    option2: "Zander",
    option3: "Flussbarsch",
  },
  {
    id: 53,
    question: "Welcher Fisch riecht nach frischer grüner Gurke?",
    option1: "Stint",
    option2: "Steinbeißer",
    option3: "Koppe",
  },
  {
    id: 54,
    question: "Welche Fischart ist anfällig für die Bauchwassersucht?",
    option1: "Karpfen",
    option2: "Forelle",
    option3: "Zander",
  },
  {
    id: 55,
    question: "Wie äußert sich die Grieẞkörnchenkrankheit?",
    option1: "Durch weiße Punkte auf dem ganzen Körper",
    option2: "Durch weiße Punkte auf den Kiemen",
    option3: "Durch Glotzaugen",
  },
  {
    id: 56,
    question: "Wo schmarotzen Karpfenläuse?",
    option1: "Auf dem ganzen Körper",
    option2: "Nur auf den Kiemen",
    option3: "Im Darm",
  },
  {
    id: 57,
    question: "Was ist eine Karpfenlaus?",
    option1:
      "Ein Kleinkrebs, der auf der Bevorzugte Haut von Karpfenfischen Karpfennahrung parisitiert.",
    option2: "Bevorzugter Parasit bei Karpfen",
    option3: "Ein Fachausdruck für Fischläuse",
  },
  {
    id: 58,
    question: "Welche Krankheit ist für den Karpfen typisch ?",
    option1: "Bauchwassersucht",
    option2: "Rotmaulseuche",
    option3: "Blumenkohlgeschwulst",
  },
  {
    id: 59,
    question:
      'Im Mai fange ich einen Blei mit weißen "Körnchen" auf dem Kopf. Worum handelt es sich mit hoher Wahrscheinlichkeit?',
    option1: "Laichausschlag",
    option2: "Krankheit",
    option3: "Tarnfärbung",
  },
  {
    id: 60,
    question:
      'Was ist in der Fischerei unter dem Begriff "Messerrücken" zu verstehen?',
    option1: "Hungerform von Karpfenfischen, speziell beim Blei",
    option2: "Rücken des Blankaals",
    option3: "Bergspitzen unterseeischer Erhebungen",
  },
  {
    id: 61,
    question: "Wo parasitieren Fischegel?",
    option1: "Auf der Haut",
    option2: "Im Darm",
    option3: "In der Leibeshöhle",
  },
  {
    id: 62,
    question:
      "Worauf ist beim Kauf von Satzschleien und vor ihrem Aussatz besonders zu achten?",
    option1: "Auf Befall mit Kiemenkrebsen (Ergasilus)",
    option2: "Auf Reinrassigkeit",
    option3: "Auf günstige Anteile von Weibchen",
  },
  {
    id: 63,
    question:
      "Welche Maßnahmen können das seuchenbiologische Gleichgewicht im Gewässer beeinträchtigen?",
    option1: "Aussetzen gebietsfremder Fische, Einleitung organischer Abwässer",
    option2: "Starke Beangelung",
    option3: "Rohrernte im Winter",
  },
  {
    id: 64,
    question:
      "Was ruft bei der sogenannten Drehkrankheit die Drehbewegung hervor?",
    option1: "Einlagerung der Parasitensporen im Gleichgewichtsorgan",
    option2: "Versuche der Fische zur Abstoßung der Parasiten",
    option3: "Ermüdungserscheinungen des Fisches",
  },
  {
    id: 65,
    question: "Zu den Außenparasiten zählen ...?",
    option1: "Egel",
    option2: "Bandwürmer",
    option3: "Nematoden",
  },
  {
    id: 66,
    question: "Wodurch kann es zu Verpilzungen kommen?",
    option1: "Durch Verletzungen der Durch falsche Ernährung Schleimhaut",
    option2: "Durch falsche Ernährung",
    option3: "Durch Altersschwäche",
  },
  {
    id: 67,
    question:
      "Weshalb ist in vielen Gewässern Brandenburgs Aalbesatz notwendig?",
    option1: "Wegen fehlendem Aufstieg von Jungaalen.",
    option2: "Wegen zu geringer Bestände",
    option3: "Wegen der zu starken Befischung",
  },
  {
    id: 68,
    question: "Wie wird Hechtbesatz getätigt?",
    option1: "Einzeln in Ufernähe, wenn möglich über Krautbänken",
    option2: "Nur an einer Uferstelle",
    option3: "In kleinen Mengen im Freiwasser",
  },
  {
    id: 69,
    question:
      "Die Quappenbestände im Land Brandenburg sind stark zurückgegangen. Weshalb?",
    option1: "Die Vielzahl der Wehre versperrt die Wege zu den Laichgebieten.",
    option2: "Sie finden zu wenig Futter",
    option3: "Sie werden zu stark beangelt",
  },
  {
    id: 70,
    question: "Wie kann ich Zanderbestände ohne Besatz in einem See fördern?",
    option1: "Einbringen von Zanderlaichnestern",
    option2: "Füttern mit Fischabfällen.",
    option3: "Anbringen von künstlichen Lichtquellen an den Laichplätzen.",
  },
  {
    id: 71,
    question: "Welche Naturnahrung bevorzugt der Karpfen?",
    option1: "Larven der Zuckmücke",
    option2: "Fischbrut",
    option3: "Anflugnahrung",
  },
  {
    id: 72,
    question: "Wo fressen Fische mit unterständigem Maul vorwiegend?",
    option1: "Am Grund",
    option2: "An der Oberfläche",
    option3: "Im Freiwasser",
  },
  {
    id: 73,
    question: "Welche Fischnährtiere leben in der Bodenzone?",
    option1: "Larven der Roten Zuckmücke",
    option2: "Wasserflöhe (Daphnien)",
    option3: "Hüpferlinge (Copepoden)",
  },
  {
    id: 74,
    question: "Fischbrut ernährt sich vorwiegend...",
    option1: "von tierischem Plankton.",
    option2: "von kleinen Schnecken und Muscheln.",
    option3: "von am Boden lebenden Nährtieren",
  },
  {
    id: 75,
    question: "Was wird auch als Sprock bezeichnet?",
    option1: "Köcherfliegenlarven",
    option2: "Libellenlarven",
    option3: "Eintagsfliegenlarven",
  },
  {
    id: 76,
    question: "Wann benötigt ein Fisch mehr Sauerstoff?",
    option1: "Bei hoher Wassertemperatur",
    option2: "Bei niedriger Wassertemperatur",
    option3: "Er verbraucht immer gleich viel Sauerstoff",
  },
  {
    id: 77,
    question:
      'Wie entstehen nach heutigem Erkenntnisstand die Aalformen "Breitkopf" und "Spitzkopf"?',
    option1: "Durch das vorhandene Nahrungsangebot im Gewässer",
    option2: "Durch unterschiedliche Laichplätze",
    option3: "Durch spezielle Erbfaktoren",
  },
  {
    id: 78,
    question: "Welche der Fischarten ernährt sich ausschließlich von Plankton?",
    option1: "Kleine Maräne",
    option2: "Grundling",
    option3: "Karpfen",
  },
  {
    id: 79,
    question:
      "Bei welcher Wassertemperatur ist der Karpfen am fressfreudigsten?",
    option1: "Bei 20-25 Grad Celsius",
    option2: "Bei 12–15 Grad Celsius",
    option3: "Bei 8–12 Grad Celsius",
  },
  {
    id: 80,
    question:
      "Warum haben gute Aalgewässer oftmals einen schlechten Krebsbestand?",
    option1: "Der Aal frisst Krebse.",
    option2: "Der Aal bevorzugt die gleiche Nahrung wie der Krebs",
    option3: "Der Aal ist der Überträger der Krebspest.",
  },
  {
    id: 81,
    question:
      'Welche der Fischarten neigen bei Massenaufkommen zur "Verbuttung"? (Kleinwüchsigkeit mit Laichreife)',
    option1: "Karausche",
    option2: "Zander",
    option3: "Forelle",
  },
  {
    id: 82,
    question: "Was ist Plankton?",
    option1:
      "Die Gesamtheit der im Freiwasserraum lebenden mit der Wasserbewegung passiv treibenden Organsysteme",
    option2: "Die Gesamtheit der Schwimmblattwasserpflan zen eines Gewässers",
    option3:
      "Die Gesamtheit der Zuckmückenlarven, Gelbrandkäfer und Libellenlarven eines Gewässers",
  },
  {
    id: 83,
    question: "Welche der Fischarten benötigen kühleres Wasser?",
    option1: "Forelle, Bachsaibling",
    option2: "Schleie, Aal",
    option3: "Karpfen, Plötze",
  },
  {
    id: 84,
    question:
      "Welche der Fischarten benötigen einen hohen Sauerstoffgehalt im Wasser?",
    option1: "Forelle, Bachsaibling",
    option2: "Plötze, Aal",
    option3: "Karpfen, Schleie",
  },
  {
    id: 85,
    question: "Welche Fische nehmen vorwiegend Oberflächennahrung auf?",
    option1: "Fische mit oberständigem Maul",
    option2: "Fische mit endständigem Maul",
    option3: "Fische mit unterständigem Maul",
  },
  {
    id: 86,
    question: "Die Entwicklung der Fischeier des Karpfens ...",
    option1: "verkürzt sich mit steigender Temperatur im Toleranzbereich.",
    option2: "verkürzt sich mit sinkender Temperatur im Toleranzbereich",
    option3:
      "hängt aufgrund des fehlenden Temperaturempfindens der Fischlarven nicht von der Temperatur ab.",
  },
  {
    id: 87,
    question: "Welche der Fischarten frisst oftmals Wasserpflanzen?",
    option1: "Rotfeder",
    option2: "Meerforelle",
    option3: "Kaulbarsch",
  },
  {
    id: 88,
    question: "Wie hoch ist die Körpertemperatur der Fische?",
    option1: "Etwa gleich der Wassertemperatur",
    option2: "Höher als die Wassertemperatur",
    option3: "Etwa gleich der Lufttemperatur",
  },
  {
    id: 89,
    question: "Was ist ein Milchner?",
    option1: "Männlicher Fisch",
    option2: "Weiblicher Fisch",
    option3: "Jungfisch",
  },
  {
    id: 90,
    question: "Warum gibt es Schonzeiten?",
    option1: "Um den Fischen eine ungestörte Laichablage zu ermöglichen.",
    option2: "Um den Uferschutz zu gewährleisten",
    option3: "Um zu verhindern, dass zu viele Fische auf den Markt kommen",
  },
  {
    id: 91,
    question: "Was ist unter dem Begriff Laichausschlag zu verstehen?",
    option1: "Ausschlag bei einigen Fischarten zur Laichzeit",
    option2: "Infektion des Laiches",
    option3: "Ausschlag bei einigen Fischarten nach der Laichzeit",
  },
  {
    id: 92,
    question: "Was versteht man unter einem Butterkrebs?",
    option1: "Einen frisch gehäuteten Krebs",
    option2: "Einen Edelkrebs im Jugendstadium",
    option3: "Einen an Krebspest erkrankten Krebs",
  },
  {
    id: 93,
    question: "Wo entwickeln sich die Eier vom Krebs?",
    option1: "An der Unterseite des Hinterleibes des weiblichen Krebses",
    option2: "In Laichgruben auf kiesigem Untergrund",
    option3: "An Wasserpflanzen angeheftet",
  },
  {
    id: 94,
    question:
      "Welche hier genannten Körperteile und Merkmale werden zur Altersbestimmung von Fischen genutzt?",
    option1:
      "Anzahl der Ringe auf Schuppen und Otolithen (Steine aus dem Gleichgewichtsorgan)",
    option2: "Anzahl der Gräten",
    option3: "Anzahl und Stellung der Rückenflossenstrahlen",
  },
  {
    id: 95,
    question:
      "Was ist hinsichtlich der Körperlänge weiblicher und männlicher Aale richtig?",
    option1: "Weibliche Aale werden länger.",
    option2: "Männliche Aale werden länger",
    option3: "Beide Geschlechter werden gleich lang",
  },
  {
    id: 96,
    question: "Wie wird die Totallänge des Fisches gemessen?",
    option1:
      "Von der Maulspitze bis zum Ende der natürlich ausgebreiteten Schwanzflosse",
    option2: "Von den Brustflossen bis zum Ansatz der Schwanzflosse",
    option3: "Von den Kiemendeckeln bis zur Afterflosse",
  },
  {
    id: 97,
    question: 'Was wird unter dem Begriff "saures Wasser" verstanden?',
    option1: "Wasser mit niedrigem pH-Wert",
    option2: "Trübes Wasser",
    option3: "Wasser mit hohem pH-Wert",
  },
  {
    id: 98,
    question: "Was versteht man unter einem neutralen pH-Wert?",
    option1: "pH-Wert von 7",
    option2: "pH-Wert über 7",
    option3: "pH-Wert unter 7",
  },
  {
    id: 99,
    question:
      "Können sich die Marmorkarpfen in Brandenburger Gewässern selbst reproduzieren?",
    option1: "Nein",
    option2: "Ja",
    option3: "Nur in warmen Sommern",
  },
  {
    id: 100,
    question: "Welche Jahreszeit ist Quappenbeißzeit?",
    option1: "Winter",
    option2: "Sommer",
    option3: "Frühjahr",
  },
  {
    id: 101,
    question: "Karpfen sind...?",
    option1: "Sommerlaicher",
    option2: "Frühjahrslaicher",
    option3: "Winterlaicher",
  },
  {
    id: 102,
    question:
      "Gehört der Silberkarpfen zu den schutzbedürftigen heimischen Fischarten?",
    option1: "Nein",
    option2: "Ja",
    option3: "Ja, aber nur in Seen",
  },
  {
    id: 103,
    question: "Welche Tiere sind Schädlinge der Fischbrut?",
    option1: "Gelbrandkäferlarven",
    option2: "Wasserflöhe",
    option3: "Tubifix",
  },
  {
    id: 104,
    question: "Welche Fischarten sind Gelegelaicher?",
    option1: "Karpfen, Plötze",
    option2: "Zander, Aal",
    option3: "Regenbogenforelle, Kleine Maräne",
  },
  {
    id: 105,
    question:
      "Welche Fischarten nutzen bevorzugt für die Eiablage in das Wasser ragende Bäume, Äste, totes Geäst usw.?",
    option1: "Zander, Barsch",
    option2: "Hecht, Bachforelle",
    option3: "Barbe, Schmerle",
  },
  {
    id: 106,
    question:
      "Welche Fische sind keine heimischen Arten in den Brandenburger Gewässern?",
    option1: "Graskarpfen, Marmorkarpfen, Silberkarpfen",
    option2: "Karausche, Aland, Bitterling",
    option3: "Rotfeder, Schlammpeitzger, Gründling",
  },
  {
    id: 107,
    question: "Kann an den Schuppen das Alter der Fische abgelesen werden?",
    option1: "Ja, anhand der Verdichtungszonen (Ringe)",
    option2: "Nein",
    option3: "Ja, aber nur bei Rognern",
  },
  {
    id: 108,
    question: "Wie alt können Karpfen werden?",
    option1: "Ca. 40 Jahre",
    option2: "Ca. 10 Jahre",
    option3: "Über 150 Jahre",
  },
  {
    id: 109,
    question: "Welcher Karpfenfisch ist nicht einheimisch?",
    option1: "Graskarpfen",
    option2: "Schleie",
    option3: "Grundling",
  },
  {
    id: 110,
    question: "Aale laichen ...?",
    option1: "einmal im Leben",
    option2: "alle 2 Jahre",
    option3: "alle 4 Jahre",
  },
  {
    id: 111,
    question: "Was sind Blankaale?",
    option1: "Aale auf der Laichwanderung",
    option2: "Tagaktive Aale",
    option3: "Jungaale",
  },
  {
    id: 112,
    question: "Die Schleie ist ein ...?",
    option1: "Krautlaicher",
    option2: "Kieslaicher",
    option3: "Bodenlaicher",
  },
  {
    id: 113,
    question:
      "Welche Fischart erreicht Stückgewichte von mehr als 10 Kilogramm?",
    option1: "Karpfen",
    option2: "Schleie",
    option3: "Grundling",
  },
  {
    id: 114,
    question: "Wo laicht der Hecht?",
    option1: "An flachen verkrauteten Uferstellen",
    option2: "Im Freiwasser",
    option3: "Im Kiesbett",
  },
  {
    id: 115,
    question: "Wann laicht der Zander?",
    option1: "Von März bis Juni",
    option2: "Von Juli bis September",
    option3: "Von Oktober bis November",
  },
  {
    id: 116,
    question:
      "Nach welcher Fischart sind große, flache, trübe Seen mit häufiger Wasserblüten benannt?",
    option1: "Zander",
    option2: "Quappe",
    option3: "Hecht",
  },
  {
    id: 117,
    question: "Welche Fischart unternimmt keine Laichwanderung?",
    option1: "Neunstachliger Stichling",
    option2: "Lachs",
    option3: "Aal",
  },
  {
    id: 118,
    question:
      "Wie heißt die in Brandenburg ursprüngliche einheimische Krebsart?",
    option1: "Edelkrebs",
    option2: "Süßwasserhummer",
    option3: "Amerikanischer Flusskrebs",
  },
  {
    id: 119,
    question: "Der Bitterling ist ein ...?",
    option1: "Schwarmfisch",
    option2: "typischer Einzelgänger",
    option3: "bitter schmeckender Fisch",
  },
  {
    id: 120,
    question:
      "Welcher Zehnfußkrebs unternimmt flussaufwärts Massenwanderungen und wird so zur Plage?",
    option1: "Wollhandkrabbe",
    option2: "Signalkrebs",
    option3: "Sumpfkrebs",
  },
];
